/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jet.set.billy;

public class App
{
    public String getGreeting()
    {
        return "Hello World!";
    }

    public static void main(String[] args)
    {
        try
        {
            Game game = new Game();
            game.run();
        }
        catch (Exception e)
        {
            System.out.println("Exception: " + e.getMessage());
        }
    }
}
