/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.l14gr07.jsb;

import java.io.IOException;
import java.net.URISyntaxException;
import java.awt.FontFormatException;

public class App
{
    public String getGreeting()
    {
        return "Hello World!";
    }

    public static void main(String[] args)
    {
        try
        {
            Game game = new Game();
            game.run();
        }
        catch (FontFormatException e)
        {
            System.out.println("Font Exception: " + e.getMessage());
        }
        catch (InterruptedException e)
        {
            System.out.println("Thread Interrupted Exception: " + e.getMessage());
        }
        catch (URISyntaxException e)
        {
            System.out.println("URI Syntax Exception: " + e.getMessage());
        }
        catch (IOException e)
        {
            System.out.println("IOException: " + e.getMessage());
        }
    }
}
